### ISSUE TITLE
python version error

### ISSUE THREAD

**Issue by palfeng** [mrlb05/Nifty4Gemini#7]
Hello, I'm a new user for Nifty4Gemini to reduce NIFS data. After I installed geminiconda following https://www.gemini.edu/observing/phase-iii/reducing-data/gemini-iraf-data-reduction-software and I download the Nifty4Gemini codes in this github, I still cannot install Nifty4Gemini since it warns that the python version is wrong (while I do have the correct version). I attach the screenshot below. Can you please advise where is wrong? Thanks!
![Screenshot 2023-05-18 at 5 09 21 PM](https://github.com/mrlb05/Nifty4Gemini/assets/16551206/22a833dd-98c3-4793-ac0e-b5b773c4873a)

**Comment by palfeng** [comment]
Ok. The above issue is solved once I downgrade my python to 2.7. But I still cannot load "import nifty" and the error is: 
>>> import nifty
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parallels/anaconda3/envs/geminiconda27/lib/python2.7/site-packages/pyraf/irafimport.py", line 116, in _irafImport
    retval = _originalImport(name, globals, locals, fromlist, level)
  File "./nifty/__init__.py", line 1, in <module>
    import pipeline.nifsPipeline as nifsPipeline
  File "/home/parallels/anaconda3/envs/geminiconda27/lib/python2.7/site-packages/pyraf/irafimport.py", line 116, in _irafImport
    retval = _originalImport(name, globals, locals, fromlist, level)
  File "nifty/pipeline/nifsPipeline.py", line 49, in <module>
    from objectoriented.getConfig import GetConfig
  File "/home/parallels/anaconda3/envs/geminiconda27/lib/python2.7/site-packages/pyraf/irafimport.py", line 116, in _irafImport
    retval = _originalImport(name, globals, locals, fromlist, level)
ImportError: No module named getConfig

I have changed that there is indeed a file call GetConfig.py in the correct path, but not sure why it is error. Can you please help? Thanks!
